export const PROJECT_DELETE_VIDEO_REQUEST = 'PROJECT_DELETE_VIDEO_REQUEST';
export const PROJECT_DELETE_VIDEO_SUCCESS = 'PROJECT_DELETE_VIDEO_SUCCESS';
export const PROJECT_DELETE_VIDEO_FAILURE = 'PROJECT_DELETE_VIDEO_FAILURE';

export const PROJECT_DELETE_VIDEO_CLEAR = 'PROJECT_DELETE_VIDEO_CLEAR';
