export const PRODUCT_DELETE_IMAGE_REQUEST = 'PRODUCT_DELETE_IMAGE_REQUEST';
export const PRODUCT_DELETE_IMAGE_SUCCESS = 'PRODUCT_DELETE_IMAGE_SUCCESS';
export const PRODUCT_DELETE_IMAGE_FAILURE = 'PRODUCT_DELETE_IMAGE_FAILURE';

export const PRODUCT_DELETE_IMAGE_CLEAR = 'PRODUCT_DELETE_IMAGE_CLEAR';
