export const PROJECT_PUBLIC_GET_ONE_REQUEST = 'PROJECT_PUBLIC_GET_ONE_REQUEST';
export const PROJECT_PUBLIC_GET_ONE_SUCCESS = 'PROJECT_PUBLIC_GET_ONE_SUCCESS';
export const PROJECT_PUBLIC_GET_ONE_FAILURE = 'PROJECT_PUBLIC_GET_ONE_FAILURE';
export const PROJECT_PUBLIC_GET_ONE_CLEAR = 'PROJECT_PUBLIC_GET_ONE_CLEAR';
