export const PRODUCT_PUBLIC_GET_ALL_REQUEST = 'PRODUCT_PUBLIC_GET_ALL_REQUEST';
export const PRODUCT_PUBLIC_GET_ALL_SUCCESS = 'PRODUCT_PUBLIC_GET_ALL_SUCCESS';
export const PRODUCT_PUBLIC_GET_ALL_FAILURE = 'PRODUCT_PUBLIC_GET_ALL_FAILURE';
