export const PRODUCT_DELETE_VIDEO_REQUEST = 'PRODUCT_DELETE_VIDEO_REQUEST';
export const PRODUCT_DELETE_VIDEO_SUCCESS = 'PRODUCT_DELETE_VIDEO_SUCCESS';
export const PRODUCT_DELETE_VIDEO_FAILURE = 'PRODUCT_DELETE_VIDEO_FAILURE';

export const PRODUCT_DELETE_VIDEO_CLEAR = 'PRODUCT_DELETE_VIDEO_CLEAR';
