export const PROJECT_DELETE_IMAGE_REQUEST = 'PROJECT_DELETE_IMAGE_REQUEST';
export const PROJECT_DELETE_IMAGE_SUCCESS = 'PROJECT_DELETE_IMAGE_SUCCESS';
export const PROJECT_DELETE_IMAGE_FAILURE = 'PROJECT_DELETE_IMAGE_FAILURE';

export const PROJECT_DELETE_IMAGE_CLEAR = 'PROJECT_DELETE_IMAGE_CLEAR';
