export const PROJECT_UPDATE_IMAGE_REQUEST = 'PROJECT_UPDATE_IMAGE_REQUEST';
export const PROJECT_UPDATE_IMAGE_SUCCESS = 'PROJECT_UPDATE_IMAGE_SUCCESS';
export const PROJECT_UPDATE_IMAGE_FAILURE = 'PROJECT_UPDATE_IMAGE_FAILURE';
export const PROJECT_UPDATE_IMAGE_CLEAR = 'PROJECT_UPDATE_IMAGE_CLEAR';
