export const CLIENT_DELETE_REQUEST = 'CLIENT_DELETE_REQUEST';
export const CLIENT_DELETE_SUCCESS = 'CLIENT_DELETE_SUCCESS';
export const CLIENT_DELETE_FAILURE = 'CLIENT_DELETE_FAILURE';

export const CLIENT_DELETE_CLEAR = 'CLIENT_DELETE_CLEAR';
