export const PROJECT_CREATE_IMAGE_REQUEST = 'PROJECT_CREATE_IMAGE_REQUEST';
export const PROJECT_CREATE_IMAGE_SUCCESS = 'PROJECT_CREATE_IMAGE_SUCCESS';
export const PROJECT_CREATE_IMAGE_FAILURE = 'PROJECT_CREATE_IMAGE_FAILURE';
export const PROJECT_CREATE_IMAGE_CLEAR = 'PROJECT_CREATE_IMAGE_CLEAR';
