export const PROJECT_PUBLIC_GET_ALL_REQUEST = 'PROJECT_PUBLIC_GET_ALL_REQUEST';
export const PROJECT_PUBLIC_GET_ALL_SUCCESS = 'PROJECT_PUBLIC_GET_ALL_SUCCESS';
export const PROJECT_PUBLIC_GET_ALL_FAILURE = 'PROJECT_PUBLIC_GET_ALL_FAILURE';
