export const EMPLOYEE_UPDATE_REQUEST = 'EMPLOYEE_UPDATE_REQUEST';
export const EMPLOYEE_UPDATE_SUCCESS = 'EMPLOYEE_UPDATE_SUCCESS';
export const EMPLOYEE_UPDATE_FAILURE = 'EMPLOYEE_UPDATE_FAILURE';
export const EMPLOYEE_UPDATE_CLEAR = 'EMPLOYEE_UPDATE_CLEAR';
