export const PRODUCT_UPDATE_VIDEO_REQUEST = 'PRODUCT_UPDATE_VIDEO_REQUEST';
export const PRODUCT_UPDATE_VIDEO_SUCCESS = 'PRODUCT_UPDATE_VIDEO_SUCCESS';
export const PRODUCT_UPDATE_VIDEO_FAILURE = 'PRODUCT_UPDATE_VIDEO_FAILURE';
export const PRODUCT_UPDATE_VIDEO_CLEAR = 'PRODUCT_UPDATE_VIDEO_CLEAR';
