export const EMPLOYEE_GET_ONE_REQUEST = 'EMPLOYEE_GET_ONE_REQUEST';
export const EMPLOYEE_GET_ONE_SUCCESS = 'EMPLOYEE_GET_ONE_SUCCESS';
export const EMPLOYEE_GET_ONE_FAILURE = 'EMPLOYEE_GET_ONE_FAILURE';
