export const PROJECT_UPDATE_VIDEO_REQUEST = 'PROJECT_UPDATE_VIDEO_REQUEST';
export const PROJECT_UPDATE_VIDEO_SUCCESS = 'PROJECT_UPDATE_VIDEO_SUCCESS';
export const PROJECT_UPDATE_VIDEO_FAILURE = 'PROJECT_UPDATE_VIDEO_FAILURE';
export const PROJECT_UPDATE_VIDEO_CLEAR = 'PROJECT_UPDATE_VIDEO_CLEAR';
