export const PROJECT_CREATE_VIDEO_REQUEST = 'PROJECT_CREATE_VIDEO_REQUEST';
export const PROJECT_CREATE_VIDEO_SUCCESS = 'PROJECT_CREATE_VIDEO_SUCCESS';
export const PROJECT_CREATE_VIDEO_FAILURE = 'PROJECT_CREATE_VIDEO_FAILURE';
export const PROJECT_CREATE_VIDEO_CLEAR = 'PROJECT_CREATE_VIDEO_CLEAR';
