export const PRODUCT_UPDATE_IMAGE_REQUEST = 'PRODUCT_UPDATE_IMAGE_REQUEST';
export const PRODUCT_UPDATE_IMAGE_SUCCESS = 'PRODUCT_UPDATE_IMAGE_SUCCESS';
export const PRODUCT_UPDATE_IMAGE_FAILURE = 'PRODUCT_UPDATE_IMAGE_FAILURE';
export const PRODUCT_UPDATE_IMAGE_CLEAR = 'PRODUCT_UPDATE_IMAGE_CLEAR';
