export const PRODUCT_PUBLIC_GET_ONE_REQUEST = 'PRODUCT_PUBLIC_GET_ONE_REQUEST';
export const PRODUCT_PUBLIC_GET_ONE_SUCCESS = 'PRODUCT_PUBLIC_GET_ONE_SUCCESS';
export const PRODUCT_PUBLIC_GET_ONE_FAILURE = 'PRODUCT_PUBLIC_GET_ONE_FAILURE';
export const PRODUCT_PUBLIC_GET_ONE_CLEAR = 'PRODUCT_PUBLIC_GET_ONE_CLEAR';
