export const BANK_ACCOUNT_GET_ONE_REQUEST = 'BANK_ACCOUNT_GET_ONE_REQUEST';
export const BANK_ACCOUNT_GET_ONE_SUCCESS = 'BANK_ACCOUNT_GET_ONE_SUCCESS';
export const BANK_ACCOUNT_GET_ONE_FAILURE = 'BANK_ACCOUNT_GET_ONE_FAILURE';
