export const BANK_ACCOUNT_UPDATE_REQUEST = 'BANK_ACCOUNT_UPDATE_REQUEST';
export const BANK_ACCOUNT_UPDATE_SUCCESS = 'BANK_ACCOUNT_UPDATE_SUCCESS';
export const BANK_ACCOUNT_UPDATE_FAILURE = 'BANK_ACCOUNT_UPDATE_FAILURE';
export const BANK_ACCOUNT_UPDATE_CLEAR = 'BANK_ACCOUNT_UPDATE_CLEAR';
