export const EMPLOYEE_CREATE_REQUEST = 'EMPLOYEE_CREATE_REQUEST';
export const EMPLOYEE_CREATE_SUCCESS = 'EMPLOYEE_CREATE_SUCCESS';
export const EMPLOYEE_CREATE_FAILURE = 'EMPLOYEE_CREATE_FAILURE';
export const EMPLOYEE_CREATE_CLEAR = 'EMPLOYEE_CREATE_CLEAR';
