export const PRODUCT_CREATE_VIDEO_REQUEST = 'PRODUCT_CREATE_VIDEO_REQUEST';
export const PRODUCT_CREATE_VIDEO_SUCCESS = 'PRODUCT_CREATE_VIDEO_SUCCESS';
export const PRODUCT_CREATE_VIDEO_FAILURE = 'PRODUCT_CREATE_VIDEO_FAILURE';
export const PRODUCT_CREATE_VIDEO_CLEAR = 'PRODUCT_CREATE_VIDEO_CLEAR';
