export const EMPLOYEE_GET_ALL_REQUEST = 'EMPLOYEE_GET_ALL_REQUEST';
export const EMPLOYEE_GET_ALL_SUCCESS = 'EMPLOYEE_GET_ALL_SUCCESS';
export const EMPLOYEE_GET_ALL_FAILURE = 'EMPLOYEE_GET_ALL_FAILURE';
