export const EMPLOYEE_DELETE_REQUEST = 'EMPLOYEE_DELETE_REQUEST';
export const EMPLOYEE_DELETE_SUCCESS = 'EMPLOYEE_DELETE_SUCCESS';
export const EMPLOYEE_DELETE_FAILURE = 'EMPLOYEE_DELETE_FAILURE';

export const EMPLOYEE_DELETE_CLEAR = 'EMPLOYEE_DELETE_CLEAR';
