export const USER_VERIFY_RESET_REQUEST = 'USER_VERIFY_RESET_REQUEST';
export const USER_VERIFY_RESET_SUCCESS = 'USER_VERIFY_RESET_SUCCESS';
export const USER_VERIFY_RESET_FAILURE = 'USER_VERIFY_RESET_FAILURE';

export const USER_VERIFY_RESET_CLEAR = 'USER_VERIFY_RESET_CLEAR';
