export const CLIENT_CREATE_REQUEST = 'CLIENT_CREATE_REQUEST';
export const CLIENT_CREATE_SUCCESS = 'CLIENT_CREATE_SUCCESS';
export const CLIENT_CREATE_FAILURE = 'CLIENT_CREATE_FAILURE';
export const CLIENT_CREATE_CLEAR = 'CLIENT_CREATE_CLEAR';
